"use strict";
let myName = document.getElementById('myName');
let desig = document.getElementById('desig');
let Phone = document.getElementById('Phone');
let email = document.getElementById('email');
let add = document.getElementById('add');
let Pass = document.getElementById('pass1');
let deg1 = document.getElementById('deg1');
let uni1 = document.getElementById('uni1');
let pass2 = document.getElementById('pass2');
let deg2 = document.getElementById('deg2');
let uni2 = document.getElementById('uni2');
let skill1 = document.getElementById('skill1');
let skill2 = document.getElementById('skill2');
let skill3 = document.getElementById('skill3');
let lang1 = document.getElementById('lang1');
let lang2 = document.getElementById('lang2');
let styear = document.getElementById('styear');
let endyear = document.getElementById('endyear');
let company = document.getElementById('company');
let comlocation = document.getElementById('comlocation');
let jobTitle = document.getElementById('jobTitle');
let achv1 = document.getElementById('achv1');
let achv2 = document.getElementById('achv2');
let achv3 = document.getElementById('achv3');
let submitBtn = document.getElementById('submitBtn');
let form = document.getElementById('form');
form?.addEventListener('submit', (e) => {
    e.preventDefault();
    localStorage.setItem("name", myName.value);
    localStorage.setItem("desig", myName.value);
    localStorage.setItem("Phone", myName.value);
    localStorage.setItem("email", myName.value);
    localStorage.setItem("add", myName.value);
    localStorage.setItem("pass1", myName.value);
    localStorage.setItem("deg1", myName.value);
    localStorage.setItem("uni1", myName.value);
    localStorage.setItem("pass2", myName.value);
    localStorage.setItem("deg2", myName.value);
    localStorage.setItem("uni2", myName.value);
    localStorage.setItem("skill1", myName.value);
    localStorage.setItem("skill2", myName.value);
    localStorage.setItem("skill3", myName.value);
    localStorage.setItem("lang1", myName.value);
    localStorage.setItem("lang2", myName.value);
    localStorage.setItem("styear", myName.value);
    localStorage.setItem("endyear", myName.value);
    localStorage.setItem("company", myName.value);
    localStorage.setItem("comlocation", myName.value);
    localStorage.setItem("jobTitle", myName.value);
    localStorage.setItem("achv1", myName.value);
    localStorage.setItem("achv2", myName.value);
    localStorage.setItem("achv3", myName.value);
    window.location.href = "./resume/resume.html";
});
